import type { App } from 'vue';
import {
  Button,
  Card,
  Avatar,
  Upload,
  Form,
  FormItem,
  Input,
  InputPassword,
  InputSearch,
  InputNumber,
  Textarea,
  Select,
  SelectOption,
  Switch,
  Tag,
  Badge,
  Space,
  Tooltip,
  Popconfirm,
  Modal,
  Tabs,
  TabPane,
  Descriptions,
  DescriptionsItem,
  Divider,
  Statistic,
  Checkbox,
  RadioGroup,
  Radio,
  DatePicker,
  Empty,
  Spin,
  Layout,
  LayoutSider,
  LayoutHeader,
  LayoutContent,
  LayoutFooter,
  Menu,
  MenuItem,
  MenuDivider,
  Breadcrumb,
  BreadcrumbItem,
  Dropdown,
  Row,
  Col,
  Table,
  ConfigProvider,
} from 'ant-design-vue';
import 'ant-design-vue/dist/reset.css';

export { message } from 'ant-design-vue';

const components = [
  Button, Card, Avatar, Upload,
  Form, FormItem,
  Input, InputPassword, InputSearch, InputNumber, Textarea,
  Select, SelectOption,
  Switch, Tag, Badge, Space,
  Tooltip, Popconfirm, Modal,
  Tabs, TabPane,
  Descriptions, DescriptionsItem,
  Divider, Statistic,
  Checkbox, RadioGroup, Radio,
  DatePicker, Empty, Spin,
  Layout, LayoutSider, LayoutHeader, LayoutContent, LayoutFooter,
  Menu, MenuItem, MenuDivider,
  Breadcrumb, BreadcrumbItem,
  Dropdown,
  Row, Col, Table,
  ConfigProvider,
];

export function setupAntd(app: App) {
  components.forEach(comp => app.use(comp));
}
